---
- name: Check apt last update
  stat: path=/var/cache/apt
  register: apt_cache_stat

- name: Update apt cache if needed
  apt: update_cache=yes
  when: ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12
